# Important Notes:
# fabric.mod.json's modid field cannot be expanded, you must change it manually.
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=1.0
group=com.wynprice.secretrooms
java_version=17

# Common
minecraft_version=1.20.1
mod_name=Secret Rooms Continued
mod_author=Jackbusters
mod_id=secretroomsmod
license=GNU LESSER GENERAL PUBLIC LICENSE
credits= Originally made by AbrarSyed, then continued from 1.12 - 1.19 by Wyn Price. This fork for 1.20.1+ is being developed by Jackbusters.
description=This mod adds a variety of cool blocks that camouflage themselves to the surrounding world. All of these blocks have extremely useful functions that allow you to simply hide your diamonds, or punish all who dare try to get to them. Hidden doors, pressure plates, hidden levers and more!
minecraft_version_range=[1.20.1]
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.20.1
parchment_version=2023.09.03

# Fabric
fabric_version=0.92.5+1.20.1
fabric_loader_version=0.16.13

# Forge
forge_version=47.4.0
forge_loader_version_range=[47,)

# Optional integrations
jade_version=5072729
continuity_version=5037469

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
